[project]
name = "cdp_sender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cdp-sdk>=1.32.0",
    "nats-py>=2.10.0",
    "pydantic-settings>=2.9.1",
    "tomli>=2.2.1",
    "web3>=7.10.0",
    "autofi_core"
]
