# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\rsignerGateway\"\x07\n\x05\x45mpty\"z\n\x13\x45thereumSignRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\t\x12\x18\n\x10transaction_type\x18\x04 \x01(\x03\x12\x18\n\x10transaction_data\x18\x05 \x01(\x0c\"/\n\x11\x45thereumSignReply\x12\x1a\n\x12signed_transaction\x18\x01 \x01(\x0c\">\n\x0fSignDataRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04hash\x18\x03 \x01(\x0c\"\"\n\rSignDataReply\x12\x11\n\tsignature\x18\x01 \x01(\x0c\"%\n\x11InitializeRequest\x12\x10\n\x08mnemonic\x18\x01 \x01(\t\"!\n\x0fInitializeReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\"!\n\x11GetAddressRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\"\n\x0fGetAddressReply\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t2\x98\x03\n\x0cVaultService\x12V\n\x0c\x45thereumSign\x12\".signerGateway.EthereumSignRequest\x1a .signerGateway.EthereumSignReply\"\x00\x12J\n\x08SignData\x12\x1e.signerGateway.SignDataRequest\x1a\x1c.signerGateway.SignDataReply\"\x00\x12P\n\nInitialize\x12 .signerGateway.InitializeRequest\x1a\x1e.signerGateway.InitializeReply\"\x00\x12@\n\x06Health\x12\x14.signerGateway.Empty\x1a\x1e.signerGateway.InitializeReply\"\x00\x12P\n\nGetAddress\x12 .signerGateway.GetAddressRequest\x1a\x1e.signerGateway.GetAddressReply\"\x00\x42\x45ZCgithub.com/aegis-agents/aegis-backend/src/common/grpc/signerGatewayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/aegis-agents/aegis-backend/src/common/grpc/signerGateway'
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_ETHEREUMSIGNREQUEST']._serialized_start=41
  _globals['_ETHEREUMSIGNREQUEST']._serialized_end=163
  _globals['_ETHEREUMSIGNREPLY']._serialized_start=165
  _globals['_ETHEREUMSIGNREPLY']._serialized_end=212
  _globals['_SIGNDATAREQUEST']._serialized_start=214
  _globals['_SIGNDATAREQUEST']._serialized_end=276
  _globals['_SIGNDATAREPLY']._serialized_start=278
  _globals['_SIGNDATAREPLY']._serialized_end=312
  _globals['_INITIALIZEREQUEST']._serialized_start=314
  _globals['_INITIALIZEREQUEST']._serialized_end=351
  _globals['_INITIALIZEREPLY']._serialized_start=353
  _globals['_INITIALIZEREPLY']._serialized_end=386
  _globals['_GETADDRESSREQUEST']._serialized_start=388
  _globals['_GETADDRESSREQUEST']._serialized_end=421
  _globals['_GETADDRESSREPLY']._serialized_start=423
  _globals['_GETADDRESSREPLY']._serialized_end=457
  _globals['_VAULTSERVICE']._serialized_start=460
  _globals['_VAULTSERVICE']._serialized_end=868
# @@protoc_insertion_point(module_scope)
